#!/usr/bin/env python3
"""
field_antenna.py — Take the NanoVNA to the antenna; save .s1p / PDF.

Minimal-fuss tool for at-the-antenna captures. Sweeps S11, writes a
1-port Touchstone .s1p + a one-page PDF summary (VSWR + R+jX). The
file naming includes a UTC timestamp so successive trips don't
overwrite each other.

The point: when you're at the top of the tower with the laptop, you
don't want to type a long flag list. One command, sensible defaults,
PDF you can email yourself.
"""

from __future__ import annotations
import warnings
warnings.filterwarnings("ignore", message="Unable to import Axes3D")
import argparse, sys
from datetime import datetime, timezone
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def open_vna(args):
    if args.vna == "nanovna":
        from rf_bench.nanovna import NanoVNA
        return NanoVNA(port=args.port)
    from rf_bench.hp import HP8712B
    return HP8712B(host=args.host)


def write_s1p(path, freqs_hz, s11, z0=50.0, comment_lines=None):
    with open(path, "w") as fh:
        fh.write(f"! Touchstone .s1p, generated by field_antenna.py\n")
        fh.write(f"! Date: {datetime.now(timezone.utc).isoformat()}\n")
        if comment_lines:
            for line in comment_lines: fh.write(f"! {line}\n")
        fh.write(f"# Hz S MA R {z0:g}\n")
        for i in range(len(freqs_hz)):
            mag = abs(s11[i])
            ang = np.degrees(np.angle(s11[i]))
            fh.write(f"{freqs_hz[i]:.6e}  {mag:.6e}  {ang:.4f}\n")


def main() -> int:
    p = argparse.ArgumentParser(description="At-the-antenna S11 capture.")
    p.add_argument("--vna", choices=("nanovna","hp"), default="nanovna")
    p.add_argument("--port", default="/dev/ttyACM1")
    p.add_argument("--host", default="10.1.1.70")
    p.add_argument("--start", type=float, required=True, metavar="MHZ")
    p.add_argument("--stop",  type=float, required=True, metavar="MHZ")
    p.add_argument("--points", type=int, default=401)
    p.add_argument("--average", type=int, default=2)
    p.add_argument("--label", required=True,
                   help="Antenna label, also used in the output filenames.")
    p.add_argument("--out-dir", default=".",
                   help="Directory to write files into (default: cwd)")
    args = p.parse_args()
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    safe_label = args.label.replace(" ", "_").replace("/", "_")
    base = f"{args.out_dir}/{ts}_{safe_label}"

    vna = open_vna(args)
    try:
        vna.setup_sweep(args.start*1e6, args.stop*1e6, args.points)
        vna.set_parameter("S11")
        vna.single_sweep()
        f = vna.get_frequencies()
        s11 = vna.average_s_data(args.average) if args.average > 1 else vna.get_s_data()
    finally:
        try: vna.close()
        except Exception: pass

    write_s1p(f"{base}.s1p", f, s11, comment_lines=[f"Label: {args.label}"])
    # quick PDF: VSWR + R+jX
    mag = np.clip(np.abs(s11), 0, 1-1e-6)
    vswr = (1+mag)/(1-mag)
    z = 50.0 * (1+s11)/(1-s11+1e-12)
    f_mhz = f/1e6
    fig, axes = plt.subplots(2, 1, figsize=(11, 7.5), sharex=True)
    axes[0].plot(f_mhz, np.minimum(vswr, 10), color="#1f77b4", linewidth=1.4)
    axes[0].set_ylabel("VSWR"); axes[0].grid(True, alpha=0.35)
    axes[0].set_ylim(1, 10)
    axes[1].plot(f_mhz, z.real, color="#d62728", linewidth=1.2, label="R")
    axes[1].plot(f_mhz, z.imag, color="#2ca02c", linewidth=1.2, label="X")
    axes[1].axhline(0, color="#888888", linewidth=0.6)
    axes[1].axhline(50, color="#1f77b4", linewidth=0.6, linestyle=":")
    axes[1].set_xlabel("Frequency (MHz)"); axes[1].set_ylabel("R, X (Ω)")
    axes[1].grid(True, alpha=0.35); axes[1].legend(loc="upper right", fontsize=8)
    fig.suptitle(f"Field antenna capture — {args.label}\n{ts}", fontsize=10)
    fig.tight_layout(rect=(0,0,1,0.95))
    fig.savefig(f"{base}.pdf", format="pdf")
    plt.close(fig)
    i_min = int(np.argmin(vswr))
    print(f"  Best VSWR : {vswr[i_min]:.2f}:1 @ {f_mhz[i_min]:.3f} MHz")
    print(f"  Wrote     → {base}.s1p")
    print(f"  Wrote     → {base}.pdf")
    return 0


if __name__ == "__main__":
    sys.exit(main())
